apiVersion: v1
kind: Pod
metadata:
  name: constraintpod
spec:
  containers:
  - name: sise
    image: docker4jp/simpleservice:latest
    ports:
    - containerPort: 9876
    resources:
      limits:
        cpu: "30m"
        memory: "250Mi" 
