apiVersion: v1
kind: Pod
metadata:
  name: onspecificnode
spec:
  containers:
  - name: sise
    image: docker4jp/simpleservice:0.1.0
    ports:
    - containerPort: 9876
  nodeSelector:
    shouldrun: here
